### ISSUE TITLE
gcc - warning: comparison is always true

### ISSUE THREAD

**Issue by ldpgh** [netlabtoolkit/VarSpeedServo#16]
Just FYI ...

VarSpeedServo.cpp @ 364
VarSpeedServo.cpp @ 414
if( (channel >= 0) && (channel < MAX_SERVOS) ) // ensure channel is valid
 . . . . . . . . . . ^
VarSpeedServo.cpp:364:16: warning: comparison is always true due to limited range of data type [-Wtype-limits]

A byte value is  0 ... 255 and in this case GCC is right AFAIKT.

**Comment by pvanallen** [comment]
Because this uses MAX_SERVOS, and that could change in VarSpeedServo.h:

#define MAX_SERVOS   (_Nbr_16timers  * SERVOS_PER_TIMER)

MAX_SERVOS could be less than 255, so I don't think it would be wise to eliminate this test.
