### ISSUE TITLE
Is there any pins specified that i have to use with this servo?

### ISSUE THREAD

**Issue by AshrafAkon** [netlabtoolkit/VarSpeedServo#20]
I am using a Arduino nano and I have 5 servos. Is there any special pins that have to be used in order to use this library? or can I just use any digital pin? or Do i have to use the specified pwm pins of Arduino nano?

**Comment by geoolson** [comment]
I've been testing this library on a nano and found that pins D2 through D13 and pins A0 through A5 work. Pins A0 through A5 are also numbered as pins14 through 19

**Comment by AshrafAkon** [comment]
If anyone have the same question in mind. Please open a new issue.
