### ISSUE TITLE
Error compiling for board Arduino/Genuino Mega or Mega 2560

### ISSUE THREAD

**Issue by DrAlanHenry** [netlabtoolkit/VarSpeedServo#28]
Error compiling for board Arduino/Genuino Mega or Mega 2560

Is there a fix?

**Comment by per1234** [comment]
With so little information, this report is absolutely worthless. You need to scroll up and look at the actual error messages.

When you encounter an error you'll see a button on the right side of the orange bar "Copy error messages". Click that button. Paste the error in a comment here using [code fencing](https://guides.github.com/features/mastering-markdown/).

**Comment by DrAlanHenry** [comment]
Hi per124,
My bad, Conflict error. I had:
#include <Servo.h>
#include <VarSpeedServo.h>
